version: "2"
services:
    nginx:
        build: ./.docker/nginx
        ports:
          - "8088:80"
        volumes_from:
          - php:rw
        environment:
          - NGINX_HOST=localhost
          - NGINX_PORT=80
        command: nginx -g "daemon off;"
        links:
          - php
    php:
        build: ./.docker/php
        volumes:
          - ./:/var/www:rw
        links:
          - db
    db:
        image: mysql:5.7
        ports:
          - "33068:3306"
        volumes:
          - ./.docker/data/mysql:/var/lib/mysql
        environment:
          MYSQL_ROOT_PASSWORD: 'admin'
          MYSQL_DATABASE: 'example'
          MYSQL_USER: 'example'
          MYSQL_PASSWORD: 'example'
